# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveObjCDemo' do
 
  use_frameworks!

#pod 'ReactiveObjC', '~> 3.0.0'

#pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'SDWebImage'
pod 'Masonry'
pod 'MJRefresh'
pod 'JSONModel'
pod 'Ono'
pod 'AFNetworking'
pod 'DTCoreText'
pod 'FMDB'
pod 'ReactiveCocoa', '=2.3'
pod 'FDFullscreenPopGesture'

 pod 'CocoaLumberjack'
end
